### ISSUE TITLE
Weird deadlock in chromedp

### ISSUE THREAD

**Issue by CaledoniaProject** [chromedp/chromedp#1006]
#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.7.3
$ google-chrome --version
Chromium 97.0.4692.99 snap
$ go version
go version go1.17.5 linux/amd64
```

#### What did you do? Include clear steps.

I have a weird deadlock when I take a screenshot with chromedp. To debug this problem I first implemented a signal handler for SIGQUIT and make it print the goroutine stack when signalled:

```
goroutine 7874774 [semacquire, 879 minutes]:
sync.runtime_SemacquireMutex(0x0, 0x38, 0x8000000000000000)
	/usr/local/go/src/runtime/sema.go:71 +0x25
sync.(*RWMutex).RLock(...)
	/usr/local/go/src/sync/rwmutex.go:63
github.com/chromedp/cdproto/cdp.(*Node).Attribute(0xc003a6a000, {0xb253e7, 0x2})
	/root/go/pkg/mod/github.com/chromedp/cdproto@v0.0.0-20210526005521-9e51b9051fd0/cdp/types.go:394 +0x69
github.com/chromedp/cdproto/cdp.(*Node).AttributeValue(...)
	/root/go/pkg/mod/github.com/chromedp/cdproto@v0.0.0-20210526005521-9e51b9051fd0/cdp/types.go:388
github.com/chromedp/cdproto/cdp.(*Node).xpath(0xc003a6a000, 0x1, 0x0)
	/root/go/pkg/mod/github.com/chromedp/cdproto@v0.0.0-20210526005521-9e51b9051fd0/cdp/types.go:411 +0xdb
github.com/chromedp/cdproto/cdp.(*Node).PartialXPath(...)
	/root/go/pkg/mod/github.com/chromedp/cdproto@v0.0.0-20210526005521-9e51b9051fd0/cdp/types.go:462
github.com/chromedp/chromedp.cashX.func1(0x10)
	/root/go/pkg/mod/github.com/chromedp/chromedp@v0.7.3/js.go:195 +0x2a
github.com/chromedp/chromedp.snippet({0xb4cdbb, 0x2c}, 0x7fe1ecb34878, {0xa48f40, 0xbfe400}, 0x8, {0xc0028719a8, 0x1, 0xc0028719d8})
	/root/go/pkg/mod/github.com/chromedp/chromedp@v0.7.3/js.go:188 +0x1cd
github.com/chromedp/chromedp.JavascriptAttribute.func1({0xc1c260, 0xc004350bd0}, 0xc0004de140, {0xc002348068, 0xc003323e00, 0x1})
	/root/go/pkg/mod/github.com/chromedp/chromedp@v0.7.3/query.go:935 +0x12e
github.com/chromedp/chromedp.(*Selector).Do(0xc0031fe200, {0xc1c260, 0xc004350bd0})
	/root/go/pkg/mod/github.com/chromedp/chromedp@v0.7.3/query.go:208 +0x2e9
github.com/chromedp/chromedp.Tasks.Do({0xc002871c90, 0x3, 0xa47bc0}, {0xc1c260, 0xc004350bd0})
	/root/go/pkg/mod/github.com/chromedp/chromedp@v0.7.3/chromedp.go:616 +0x83
github.com/chromedp/chromedp.Run({0xc1c228, 0xc005b43da0}, {0xc002871c90, 0x3, 0x3})
	/root/go/pkg/mod/github.com/chromedp/chromedp@v0.7.3/chromedp.go:274 +0xa5
```

At this moment, no google-chrome process is running. I'm wondering if this is a bug?

**Comment by ZekeLu** [comment]
Please provide a self-contained reproducer to show the issue.

And the implementation of the screenshot feature has been changed since `v0.7.3`. Please try the latest version first.

**Comment by CaledoniaProject** [comment]
I've updated to v0.7.6. I'll come back with the URL in problem it still occurs.
