### ISSUE TITLE
Chrome crashed when trying to open a new tab

### ISSUE THREAD

**Issue by seczoid** [chromedp/chromedp#1188]
#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.8.6
$ google-chrome --version
Chromium 109.0.5393.0
$ go version
go version go1.19.2 darwin/arm64
```

#### What did you do? Include clear steps.

```go
opts := append(chromedp.DefaultExecAllocatorOptions[:],
		chromedp.DisableGPU,
		chromedp.ExecPath("/Applications/Chromium.app/Contents/MacOS/Chromium"),
		chromedp.Flag("headless", false),
		chromedp.Flag("enable-automation", false),
		chromedp.Flag("restore-on-startup", false),
	)
	allocCtx, _ := chromedp.NewExecAllocator(context.Background(), opts...)

	ctx, cancel := chromedp.NewContext(allocCtx)
	defer cancel()
	var nodes []*cdp.Node
	selector := "#main ul li a"
	pageURL := "https://notepad-plus-plus.org/downloads/"
	if err := chromedp.Run(ctx, chromedp.Tasks{
		chromedp.Navigate(pageURL),
		chromedp.WaitReady(selector),
		chromedp.Nodes(selector, &nodes),
	}); err != nil {
		panic(err)
	}
	f := func(ctx context.Context, url string) {
		clone, cancel := chromedp.NewContext(ctx)
		defer cancel()
		fmt.Printf("%s is opening in a new tab\n", url)

		if err := chromedp.Run(clone, chromedp.Navigate(url)); err != nil {
			// do something nice with you errors!
			panic(err)
		}
	}
	for _, n := range nodes {
		u := n.AttributeValue("href")
		go f(ctx, u)
	}
```

#### What did you expect to see?
open a new tab in the browser

#### What did you see instead?

https://notepad-plus-plus.org/downloads/v8.4.2/ is opening in a new tab
https://notepad-plus-plus.org/downloads/v8.3.3/ is opening in a new tab
https://notepad-plus-plus.org/downloads/v8.4.6/ is opening in a new tab
panic: context canceled

goroutine 27 [running]:
main.testTabs.func1({0x103199720?, 0x1400031ca50?}, {0x140003ba870, 0x2f})
        tabtest.go:40 +0x120
created by main.testTabs
        tabtest.go:45 +0x428
Chrashed

**Comment by ZekeLu** [comment]
Your code is incorrect.

```diff
 package main
 
 import (
    "context"
    "fmt"
    "sync"
 
    "github.com/chromedp/cdproto/cdp"
    "github.com/chromedp/chromedp"
 )
 
 func main() {
    opts := append(chromedp.DefaultExecAllocatorOptions[:],
        chromedp.DisableGPU,
        // chromedp.ExecPath("/Applications/Chromium.app/Contents/MacOS/Chromium"),
        chromedp.Flag("headless", false),
        chromedp.Flag("enable-automation", false),
        chromedp.Flag("restore-on-startup", false),
    )
    allocCtx, _ := chromedp.NewExecAllocator(context.Background(), opts...)
 
    ctx, cancel := chromedp.NewContext(allocCtx)
    defer cancel()
    var nodes []*cdp.Node
    selector := "#main ul li a"
    pageURL := "https://notepad-plus-plus.org/downloads/"
    if err := chromedp.Run(ctx, chromedp.Tasks{
        chromedp.Navigate(pageURL),
        chromedp.WaitReady(selector),
        chromedp.Nodes(selector, &nodes),
    }); err != nil {
        panic(err)
    }
+   var wg sync.WaitGroup
    f := func(ctx context.Context, url string) {
+       defer wg.Done()
        clone, cancel := chromedp.NewContext(ctx)
        defer cancel()
        fmt.Printf("%s is opening in a new tab\n", url)
 
        if err := chromedp.Run(clone, chromedp.Navigate(url)); err != nil {
            // do something nice with you errors!
            panic(err)
        }
    }
    for _, n := range nodes {
        u := n.AttributeValue("href")
+       wg.Add(1)
        go f(ctx, u)
    }
+
+   wg.Wait()
 }
```
