### ISSUE TITLE
How to obtain all request and response information when the request fails

### ISSUE THREAD

**Issue by jiangyd** [chromedp/chromedp#1206]
#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.8.6
$ google-chrome --version
107.0.5304.107
$ go version
go version go1.18.6 windows/amd64
```

#### What did you do? Include clear steps.

```go
chromedp.ListenTarget(ctx, func(ev interface{}) {

	switch ev := ev.(type) {
	
	case *network.EventResponseReceived:
		go func() {
			c := chromedp.FromContext(ctx)

			//assert status_code not 200
			if ev.Response.Status != 200 {
				b, err := network.GetResponseBody(ev.RequestID).Do(cdp.WithExecutor(ctx, c.Target))
				if err != nil {
					fmt.Println(err)
				}
				postdata, err := network.GetRequestPostData(ev.RequestID).Do(cdp.WithExecutor(ctx, c.Target))
				if err != nil {
					fmt.Println(err)
				}
				fmt.Println("request url: ", ev.Response.URL)
				fmt.Println("request header", ev.Response.RequestHeaders)
				fmt.Println("request body", postdata)

				fmt.Println("response status_code", ev.Response.Status)
				fmt.Println("response header", ev.Response.Headers)
				fmt.Println("response body", string(b))
			}

		}()
	}
})
```

#### What did you expect to see?

I want to get all the request information and response information when the response code is not 200

#### What did you see instead?

At present, I cannot obtain the request method, and the content printed by the request header is also empty

**Comment by ZekeLu** [comment]
> I cannot obtain the request method

Get the request method from the [Network.requestWillBeSent](https://chromedevtools.github.io/devtools-protocol/tot/Network/#event-requestWillBeSent) event

> and the content printed by the request header is also empty

Sometimes the headers are only available from the [Network.responseReceivedExtraInfo](https://chromedevtools.github.io/devtools-protocol/tot/Network/#event-responseReceivedExtraInfo) event. Please note that the `Network.responseReceivedExtraInfo` event is not always emitted.

**Comment by jiangyd** [comment]
> Get the request method from the [Network.requestWillBeSent](https://chromedevtools.github.io/devtools-protocol/tot/Network/#event-requestWillBeSent) event

Network.requestWillBeSent has a request method, but I use the switch to match. When I match network.EventResponseReceived, Network RequestWillBeSent does not exist any longer, and requestWillBeSent and EventResponseReceived do not always appear together

**Comment by ZekeLu** [comment]
```go
package main

import (
	"context"
	"fmt"

	"github.com/chromedp/cdproto/network"
	"github.com/chromedp/chromedp"
)

func main() {
	ctx, cancel := chromedp.NewContext(context.Background())
	defer cancel()

	type networkEvents struct {
		requestWillBeSent         *network.EventRequestWillBeSent
		responseReceived          *network.EventResponseReceived
		responseReceivedExtraInfo *network.EventResponseReceivedExtraInfo
	}

	m := make(map[network.RequestID]networkEvents)

	chromedp.ListenTarget(ctx, func(ev interface{}) {
		switch ev := ev.(type) {
		case *network.EventRequestWillBeSent:
			e, ok := m[ev.RequestID]
			if ok {
				e.requestWillBeSent = ev
			} else {
				e = networkEvents{
					requestWillBeSent: ev,
				}
			}
			m[ev.RequestID] = e
		case *network.EventResponseReceived:
			e, ok := m[ev.RequestID]
			if ok {
				e.responseReceived = ev
			} else {
				e = networkEvents{
					responseReceived: ev,
				}
			}
			m[ev.RequestID] = e
		case *network.EventResponseReceivedExtraInfo:
			e, ok := m[ev.RequestID]
			if ok {
				e.responseReceivedExtraInfo = ev
			} else {
				e = networkEvents{
					responseReceivedExtraInfo: ev,
				}
			}
			m[ev.RequestID] = e
		case *network.EventLoadingFinished:
			if e, ok := m[ev.RequestID]; ok {
				headers := e.responseReceived.Response.Headers
				if e.responseReceivedExtraInfo != nil {
					headers = e.responseReceivedExtraInfo.Headers
				}
				fmt.Printf("%s %s\n%v\n", e.requestWillBeSent.Request.Method, e.requestWillBeSent.Request.URL, headers)
			}
		}
	})

	err := chromedp.Run(ctx,
		chromedp.Navigate("https://github.com/chromedp/chromedp/issues/1206"),
	)
	if err != nil {
		panic(err)
	}
}
```

**Comment by jiangyd** [comment]
> 

There may be some problems in the code. The map data volume will be very large. I need to start another goroutine to traverse the map and find the http status_ If the code is not 200, I need to traverse the map every time. The performance is estimated to be poor

**Comment by ZekeLu** [comment]
The example just shows that the desired information can be retrieved like this. You have to address other issues (including performance issues) yourself.

**Comment by jiangyd** [comment]
> The example just shows that the desired information can be retrieved like this. You should not copy the code directly. You have to change the code according to your use case.

I modified the code and reported an error after running for a while


```
package main

import (
	"context"
	"fmt"
	"sync"
	"time"

	"github.com/chromedp/cdproto/cdp"
	"github.com/chromedp/cdproto/network"
	"github.com/chromedp/cdproto/target"
	"github.com/chromedp/chromedp"
)

var tabs []*target.Info
var M sync.Mutex

func main() {

	browserContext, cancel := chromedp.NewExecAllocator(context.Background(), chromedp.Flag("incognito", true), chromedp.Flag("no-first-run", true), chromedp.Flag("network_log.preserve-log", true))
	defer cancel()
	ctx, cancel := chromedp.NewContext(browserContext)
	defer cancel()
	gotException := make(chan bool, 1)
	chromedp.Run(ctx)
	type networkEvents struct {
		requestWillBeSent         *network.EventRequestWillBeSent
		responseReceived          *network.EventResponseReceived
		responseReceivedExtraInfo *network.EventResponseReceivedExtraInfo
		requestBody               string
		responseBody              string
	}

	for {

		tags, err := chromedp.Targets(ctx)

		if err != nil {
			fmt.Println(err)
		}
		for _, tab := range tags {

			if tab.Type == "page" && !exist(tab) {
				tabs = append(tabs, tab)

				go func(ctx context.Context, tid target.ID) {
					m := make(map[network.RequestID]networkEvents)
					ctx, cancel := chromedp.NewContext(ctx, chromedp.WithTargetID(tid))
					defer cancel()
					// This is needed so that it will attach to the target (tab).
					chromedp.Run(ctx)
					chromedp.ListenTarget(ctx, func(ev interface{}) {

						switch ev := ev.(type) {
						case *network.EventRequestWillBeSent:
							go func() {
								M.Lock()
								e, ok := m[ev.RequestID]
								if ok {
									e.requestWillBeSent = ev
								} else {
									e = networkEvents{
										requestWillBeSent: ev,
									}
								}
								m[ev.RequestID] = e
								M.Unlock()
							}()

						case *network.EventResponseReceivedExtraInfo:
							go func() {
								M.Lock()
								e, ok := m[ev.RequestID]
								if ok {
									e.responseReceivedExtraInfo = ev
								} else {
									e = networkEvents{
										responseReceivedExtraInfo: ev,
									}
								}
								m[ev.RequestID] = e
								M.Unlock()
							}()

						case *network.EventLoadingFinished:
							go func() {
								M.Lock()
								if e, ok := m[ev.RequestID]; ok {
									if e.responseReceived.Response.Status != 200 {
										fmt.Println(e.requestWillBeSent.Request.URL)
										fmt.Println(e.requestWillBeSent.Request.URL)
										fmt.Println(e.requestWillBeSent.Request.Headers)
										fmt.Println(e.requestWillBeSent.Request.Method)
										fmt.Println(e.requestBody)

										fmt.Println(e.responseReceived.Response.Status)
										fmt.Println(e.responseReceived.Response.Headers)
										fmt.Println(e.responseBody)
									}
								}
								M.Unlock()
							}()

						case *network.EventResponseReceived:
							go func() {
								M.Lock()
								c := chromedp.FromContext(ctx)

								// //assert status_code not 200
								var requestBody string
								var responseBody []byte
								if ev.Response.Status != 200 {
									responseBody, err = network.GetResponseBody(ev.RequestID).Do(cdp.WithExecutor(ctx, c.Target))
									if err != nil {
										fmt.Println(err)
									}
									requestBody, err = network.GetRequestPostData(ev.RequestID).Do(cdp.WithExecutor(ctx, c.Target))
									if err != nil {
										fmt.Println(err)
									}
								}
								e, ok := m[ev.RequestID]
								if ok {
									e.responseReceived = ev
									e.requestBody = string(requestBody)
									e.responseBody = string(responseBody)
								} else {
									e = networkEvents{
										responseReceived: ev,
										requestBody:      string(requestBody),
										responseBody:     string(responseBody),
									}
								}
								m[ev.RequestID] = e
								M.Unlock()

							}()

						default:
							fmt.Println("no event")
						}
					})
					// This is needed otherwise the goroutine ends here.
					<-ctx.Done()
				}(ctx, tab.TargetID)
			}
		}
		time.Sleep(time.Second * 1)
	}
	<-gotException
}

func exist(v *target.Info) bool {
	for _, tab := range tabs {
		if v.TargetID == tab.TargetID {
			return true
		}
	}
	return false
}

```

**error info：**
```
...
{"code":406,"errorCode":"innerCorestone.auth.noSuchEmail","message":"No Such Email"}
no event
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x38 pc=0x3b9c85]

goroutine 1332 [running]:
main.main.func1.1.3()
        D:/mygo/ne/main.go:151 +0x125
created by main.main.func1.1
        D:/mygo/ne/main.go:148 +0xc5
exit status 2
```

**Comment by ZekeLu** [comment]
Please run your add with the `-race` flag to see whether there is a [data race](https://go.dev/doc/articles/race_detector).

It looks like there is not pointer dereference on line 151. Is the code posted here is the same as the one that you run?

```
   145					}(ctx, tab.TargetID)
   146				}
   147			}
   148			time.Sleep(time.Second * 1)
   149		}
   150		<-gotException
   151	}
   152	
   153	func exist(v *target.Info) bool {
```

**Comment by jiangyd** [comment]
> Please run your add with the `-race` flag to see whether there is a [data race](https://go.dev/doc/articles/race_detector).

I tried to use race and found no errors. I modified the code to increase printing and found problems, but I don't know why this happens,

```
151     fmt.Printf("%#v\n", e)
152     if e.responseReceived.Response.Status != 200 {
```

Network. EventResponseReceived is nil, which should not be empty according to the principle. This should be monitored on the network The EventLoadingFinished event has been written
```
main.networkEvents{requestWillBeSent:(*network.EventRequestWillBeSent)(0xc0005bc360), responseReceived:(*network.EventResponseReceived)(nil), responseReceivedExtraInfo:(*network.EventResponseReceivedExtraInfo)(0xc00015ef00), requestBody:"", responseBody:""}
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0xbe5d56]

goroutine 1447 [running]:
main.main.func1.1.3()
        D:/mygo/ne/main.go:152 +0x1f6
created by main.main.func1.1
        D:/mygo/ne/main.go:148 +0x186
exit status 2
```

**Comment by ZekeLu** [comment]
It could be nil because the event could be emitted before the event listener is set up.

**Comment by jiangyd** [comment]
> It could be nil because the event could be emitted before the event listener is set up.

No, I don't belong to this situation. The code runs for a while before this situation occurs. I guess it may be related to goroutine. Some goroutines are executed first, while others are not

**Comment by ZekeLu** [comment]
It seems that the provided source code is not the one that you actually run. I don't have further suggestion to provide based on the current information. And I don't see there is anything wrong in chromedp. Closing. Please reopen this issue if you can provide a self-contained demo to show the issue. Thank you!
