### ISSUE TITLE
Panic on nil browser object in `newSession`

### ISSUE THREAD

**Issue by jeffreystoke** [chromedp/chromedp#340]
#### What versions are you running?

```bash
$ go list -m github.com/chromedp/chromedp

# github.com/chromedp/chromedp v0.2.0 => github.com/chromedp/chromedp v0.2.0

$ chromium --version

# Chromium 72.0.3626.121 Built on Raspbian , running on Raspbian 9.9

$ go version

# go version go1.12.4 darwin/amd64
```

#### What did you do?

call `chromedp.Run` with actions

```go
err := chromedp.Run(cdpCtx, tryAuth(p.username, p.password, &finalTitle)...)
if err != nil {
	return err
}

func tryAuth(username, password string, finalTitle *string) chromedp.Tasks {
	return chromedp.Tasks{
		chromedp.Navigate(authURL),

		// wait until all required fields visible
		chromedp.WaitVisible(usernameQuery, chromedp.ByQuery),
		chromedp.WaitVisible(passwordQuery, chromedp.ByQuery),
		chromedp.WaitVisible(submitQuery, chromedp.ByQuery),
		// fill form
		chromedp.SendKeys(usernameQuery, username, chromedp.ByQuery),
		chromedp.SendKeys(passwordQuery, password, chromedp.ByQuery),
		// submit form
		chromedp.Click(submitQuery, chromedp.ByQuery),
		chromedp.WaitNotPresent(usernameQuery, chromedp.ByQuery),
		// get site title as result
		chromedp.Title(finalTitle),
	}
}
```

#### What did you expect to see?

`chromedp.Run` return an error or nil

#### What did you see instead?

```text
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x4 pc=0x12668]

goroutine 1 [running]:
github.com/chromedp/chromedp.(*Browser).Execute(0x214e0c0, 0x661168, 0x207df20, 0x59ccec, 0x11, 0x0, 0x0, 0x65cb00, 0x2082050, 0x207b128, ...)
	/repos/personal/cdp-test/vendor/github.com/chromedp/chromedp/browser.go:167 +0x9c
github.com/chromedp/cdproto/target.(*GetTargetsParams).Do(0x204dd24, 0x661168, 0x207df20, 0x65ccb0, 0x214e0c0, 0x0, 0x53d801, 0x1a, 0x0, 0x1d)
	/repos/personal/cdp-test/vendor/github.com/chromedp/cdproto/target/target.go:412 +0x74
github.com/chromedp/chromedp.(*Context).newSession(0x2120400, 0x661168, 0x207df20, 0x2082e90, 0x4)
	/repos/personal/cdp-test/vendor/github.com/chromedp/chromedp/chromedp.go:201 +0x44c
github.com/chromedp/chromedp.Run(0x661168, 0x207df20, 0x209eaa0, 0x9, 0x9, 0x209eaa0, 0x9)
	/repos/personal/cdp-test/vendor/github.com/chromedp/chromedp/chromedp.go:189 +0xf4
main.run.func1(0x204de58, 0x661148, 0x20eff80, 0x204de6c, 0x207af00, 0x0, 0x0)
	/repos/personal/cdp-test/main.go:103 +0x334
main.run(0x661148, 0x20eff80)
	/repos/personal/cdp-test/main.go:109 +0xf8
main.main.func1(0x20d4140, 0x207d440, 0x0, 0x3)
	/repos/personal/cdp-test/main.go:58 +0x84
github.com/spf13/cobra.(*Command).execute(0x20d4140, 0x207c0e8, 0x3, 0x3, 0x20d4140, 0x207c0e8)
	/repos/personal/cdp-test/vendor/github.com/spf13/cobra/command.go:766 +0x204
github.com/spf13/cobra.(*Command).ExecuteC(0x20d4140, 0xa543b0, 0x595bb8, 0x7)
	/repos/personal/cdp-test/vendor/github.com/spf13/cobra/command.go:852 +0x22c
github.com/spf13/cobra.(*Command).Execute(...)
	/repos/personal/cdp-test/vendor/github.com/spf13/cobra/command.go:800
main.main()
	/repos/personal/cdp-test/main.go:72 +0x370
```

This panic seems impossible to happen, and everything works on my `darwin/amd64` machine.

I tried to fix this using custom `chromedp.Target`, but with current api design, it's also impossibe to make it.

In brief: A nil browser object `b` was invoked when increasing id `id := atomic.AddInt64(&b.next, 1)`

Thank you for this awesome project, which helped me out from doing cross compilation in nodejs.

**Comment by mvdan** [comment]
Can you reproduce this with master? Also, please provide a full program to reproduce this bug, as otherwise it's very hard to debug.

**Comment by jeffreystoke** [comment]
Sorry for the late reply.

I can confirm `v0.3.0` fixed this panic issue, thank you!
