### ISSUE TITLE
Stuck in GetLayoutMetrics taking screenshot

### ISSUE THREAD

**Issue by tmm1** [chromedp/chromedp#514]
I have a simple method to take a page screenshot:

```
		chromedp.ActionFunc(func(ctx context.Context) error {
			_, _, contentRect, err := page.GetLayoutMetrics().Do(ctx)
			if err != nil {
				return err
			}
			v := page.Viewport{
				X:      contentRect.X,
				Y:      contentRect.Y,
				Width:  contentRect.Width,
				Height: contentRect.Height,
				Scale:  1,
			}
			buf, err := page.CaptureScreenshot().WithClip(&v).Do(ctx)
			if err != nil {
				return err
			}

			return ioutil.WriteFile("screenshot.png", buf, 0644)
		}),
```

It appears to be getting stuck:

```
goroutine 2397 [select, 2 minutes]:
github.com/chromedp/chromedp.(*Target).Execute(0xc0000f0a20, 0x16ff9e0, 0xc000701590, 0x147ea53, 0x15, 0x0, 0x0, 0x16e1240, 0xc0006a6ee0, 0x1, ...)
	github.com/chromedp/chromedp@v0.5.2-0.20191018223219-1a34c61f7847/target.go:149 +0x435
github.com/chromedp/cdproto/cdp.Execute(0x16ff9e0, 0xc000701590, 0x147ea53, 0x15, 0x0, 0x0, 0x16e1240, 0xc0006a6ee0, 0x7263733d6e6f6974, 0x746f68736e6565)
	github.com/chromedp/cdproto@v0.0.0-20191013005325-ffea6b31d538/cdp/types.go:48 +0xed
github.com/chromedp/cdproto/page.(*GetLayoutMetricsParams).Do(0xc000886648, 0x16ff9e0, 0xc000701590, 0x0, 0x0, 0xc000d309a0, 0xc000b0bad0, 0x30)
	github.com/chromedp/cdproto@v0.0.0-20191013005325-ffea6b31d538/page/page.go:402 +0x81
```

>Chromium 77.0.3865.120

**Comment by tmm1** [comment]
Replicated with latest chromedp and cdproto as well.

```
goroutine 1 [select]:
github.com/chromedp/chromedp.(*Target).Execute(0xc0006f8120, 0xe46b60, 0xc00068e6f0, 0xcbc4bc, 0x15, 0x0, 0x0, 0xe37d80, 0xc0001d4be0, 0x1, ...)
	/Users/tmm1/go/pkg/mod/github.com/chromedp/chromedp@v0.5.2-0.20191018223219-1a34c61f7847/target.go:149 +0x435
github.com/chromedp/cdproto/cdp.Execute(0xe46b60, 0xc00068e6f0, 0xcbc4bc, 0x15, 0x0, 0x0, 0xe37d80, 0xc0001d4be0, 0x7263733d6e6f6974, 0x746f68736e6565)
	/Users/tmm1/go/pkg/mod/github.com/chromedp/cdproto@v0.0.0-20191114225735-6626966fbae4/cdp/types.go:48 +0xed
github.com/chromedp/cdproto/page.(*GetLayoutMetricsParams).Do(0xc000821040, 0xe46b60, 0xc00068e6f0, 0x0, 0x0, 0xc000184c20, 0xc000094030, 0x30)
	/Users/tmm1/go/pkg/mod/github.com/chromedp/cdproto@v0.0.0-20191114225735-6626966fbae4/page/page.go:402 +0x81
```

Does not happen in headless mode, so something about having a GUI is causing issues here..

**Comment by tmm1** [comment]
I tried to remove the `GetLayoutMetrics` and `WithClip`, but it still hangs sometimes in the screenshot:

```
goroutine 1 [select]:
github.com/chromedp/chromedp.(*Target).Execute(0xc000720120, 0xe469e0, 0xc000387890, 0xcbdc06, 0x16, 0xe37840, 0xc0003878c0, 0xe37860, 0xc0003d4ac0, 0x1, ...)
	/Users/tmm1/go/pkg/mod/github.com/chromedp/chromedp@v0.5.2-0.20191018223219-1a34c61f7847/target.go:149 +0x435
github.com/chromedp/cdproto/cdp.Execute(0xe469e0, 0xc000387890, 0xcbdc06, 0x16, 0xe37840, 0xc0003878c0, 0xe37860, 0xc0003d4ac0, 0xc646e0, 0x746f68736e6501)
	/Users/tmm1/go/pkg/mod/github.com/chromedp/cdproto@v0.0.0-20191114225735-6626966fbae4/cdp/types.go:48 +0xed
github.com/chromedp/cdproto/page.(*CaptureScreenshotParams).Do(0xc0003878c0, 0xe469e0, 0xc000387890, 0x0, 0x0, 0x30, 0xc000387890, 0xb8bf80)
	/Users/tmm1/go/pkg/mod/github.com/chromedp/cdproto@v0.0.0-20191114225735-6626966fbae4/page/page.go:140 +0x8f
```

**Comment by tmm1** [comment]
I tried v0.4.2 6034fc4 and it works fine.

The next commit which switched to the flatten protocol (e8664255) hangs as does master.

cc @kenshaw

**Comment by tmm1** [comment]
Used chromedp.WithDebugf and it shows the response coming back but it is never routed back to the code:

```
2019/11/25 16:49:17 -> {"id":22,"sessionId":"71535D4147B564084E9D36D488EFE9B4","method":"Page.getLayoutMetrics"}
2019/11/25 16:49:17 <- {"id":22,"result":{"layoutViewport":{"pageX":0,"pageY":0,"clientWidth":1050,"clientHeight":885},"visualViewport":{"offsetX":0,"offsetY":0,"pageX":0,"pageY":0,"clientWidth":1050,"clientHeight":885,"scale":1,"zoom":1},"contentSize":{"x":0,"y":0,"width":1050,"height":885}},"sessionId":"71535D4147B564084E9D36D488EFE9B4"}




^\^\
SIGQUIT: quit
PC=0x45c001 m=0 sigcode=128

goroutine 0 [idle]:
runtime.futex(0x1425428, 0x80, 0x0, 0x0, 0x151600000000, 0x1516ff411708, 0x7fff341177e8, 0x4260ad, 0x7fff341177f8, 0x40a81f, ...)
	/usr/local/Cellar/go/1.13.4/libexec/src/runtime/sys_linux_amd64.s:535 +0x21
runtime.futexsleep(0x1425428, 0x151600000000, 0xffffffffffffffff)
	/usr/local/Cellar/go/1.13.4/libexec/src/runtime/os_linux.go:44 +0x46
runtime.notesleep(0x1425428)
	/usr/local/Cellar/go/1.13.4/libexec/src/runtime/lock_futex.go:151 +0x9f
runtime.stopm()
	/usr/local/Cellar/go/1.13.4/libexec/src/runtime/proc.go:1928 +0xc0
runtime.findrunnable(0xc00003e500, 0x0)
	/usr/local/Cellar/go/1.13.4/libexec/src/runtime/proc.go:2391 +0x53f
runtime.schedule()
	/usr/local/Cellar/go/1.13.4/libexec/src/runtime/proc.go:2524 +0x2be
runtime.park_m(0xc0000a6c00)
	/usr/local/Cellar/go/1.13.4/libexec/src/runtime/proc.go:2610 +0x9d
runtime.mcall(0x0)
	/usr/local/Cellar/go/1.13.4/libexec/src/runtime/asm_amd64.s:318 +0x5b

goroutine 1 [select]:
github.com/chromedp/chromedp.(*Target).Execute(0xc000030240, 0xe47f20, 0xc000623cb0, 0xcbd6ce, 0x15, 0x0, 0x0, 0xe39140, 0xc000453a80, 0x1, ...)
	/Users/tmm1/go/pkg/mod/github.com/chromedp/chromedp@v0.5.2-0.20191114231622-97580065bae3/target.go:149 +0x435
github.com/chromedp/cdproto/cdp.Execute(0xe47f20, 0xc000623cb0, 0xcbd6ce, 0x15, 0x0, 0x0, 0xe39140, 0xc000453a80, 0x7263733d6e6f6974, 0x746f68736e6565)
	/Users/tmm1/go/pkg/mod/github.com/chromedp/cdproto@v0.0.0-20191114225735-6626966fbae4/cdp/types.go:48 +0xed
github.com/chromedp/cdproto/page.(*GetLayoutMetricsParams).Do(0xc0008ff008, 0xe47f20, 0xc000623cb0, 0x0, 0x0, 0x40bd06, 0xc000623cb0, 0x30)
	/Users/tmm1/go/pkg/mod/github.com/chromedp/cdproto@v0.0.0-20191114225735-6626966fbae4/page/page.go:402 +0x81
```

**Comment by tmm1** [comment]
Hmm looks like f7283c18 might have fixed this issue.

**Comment by mvdan** [comment]
That could explain it. The previous version used to sometimes drop targets when it shouldn't, which means we would stop paying attention to received events and responses. This could easily lead to deadlocks depending on what site you were visiting.

Let's reopen if this issue appears again.

**Comment by tmm1** [comment]
> The previous version used to sometimes drop targets when it shouldn't, which means we would stop paying attention to received events and responses.

I'm trying to figure out where in the diff this was fixed. What was dropping targets before?

**Comment by mvdan** [comment]
The commit message and original issue contain some more context, I think.
