### ISSUE TITLE
buffer grow leads to its reduce

### ISSUE THREAD

**Issue by maxjust** [chromedp/chromedp#870]
In some cases chromedp crashes, I think it`s try to call wsutil.Grow with reduced size of current buffer size. 
Panic stacktrace: 
```
panic: wsutil: buffer grow leads to its reduce                              
goroutine 42 [running]:                                                     
github.com/gobwas/ws/wsutil.(*Writer).Grow(0xc0004c22e8, 0x1b)              
        /home/max/go/pkg/mod/github.com/gobwas/ws@v1.1.0-rc.5/wsutil/writer.
github.com/gobwas/ws/wsutil.(*Writer).Write(0xc0004c22e8, 0xc000ad4000, 0x8d
        /home/max/go/pkg/mod/github.com/gobwas/ws@v1.1.0-rc.5/wsutil/writer.
net.(*Buffers).WriteTo(0xc0328f45c0, 0xee9ec0, 0xc0004c22e8, 0x1ffad, 0x1ffa
        /usr/local/go/src/net/net.go:675 +0xd9                              
github.com/mailru/easyjson/buffer.(*Buffer).DumpTo(0xc0004c2410, 0xee9ec0, 0
        /home/max/go/pkg/mod/github.com/mailru/easyjson@v0.7.7/buffer/pool.g
github.com/mailru/easyjson/jwriter.(*Writer).DumpTo(...)                    
        /home/max/go/pkg/mod/github.com/mailru/easyjson@v0.7.7/jwriter/write
github.com/chromedp/chromedp.(*Conn).Write(0xc0004c2240, 0xef56a0, 0xc000928
        /home/max/go/pkg/mod/github.com/chromedp/chromedp@v0.7.3/conn.go:137
github.com/chromedp/chromedp.(*Browser).run(0xc0006bb900, 0xef56a0, 0xc00092
        /home/max/go/pkg/mod/github.com/chromedp/chromedp@v0.7.3/browser.go:
created by github.com/chromedp/chromedp.NewBrowser                          
        /home/max/go/pkg/mod/github.com/chromedp/chromedp@v0.7.3/browser.go:
%# v &{info systemd 45 0xc0000c8820 0xc0000c8870 0xc0006bc760 0xc000495950}
```

**Comment by ZekeLu** [comment]
The issue has been fixed in github.com/gobwas/ws, but it's not released yet. I will  update the dependency once github.com/gobwas/ws@v1.0.5 is released.
Thanks!

**Comment by maxjust** [comment]
@ZekeLu Hi, gobwas today released new version include a panic fix which I wrote. Can you please update dependencies and publish a new release?

**Comment by ZekeLu** [comment]
@maxjust Thanks! I'm going to prepare the new release. And will release it once it's approved by @kenshaw.

**Comment by ZekeLu** [comment]
`v0.7.4` is released. :tada:
